### ISSUE TITLE
Spam by SSL warning in console

### ISSUE THREAD

**Issue by spikegaming100** [EnvyWare/UltimatePokeBuilder#11]
log: [latest.log](https://github.com/EnvyWare/UltimatePokeBuilder/files/9867588/latest.log)
![изображение](https://user-images.githubusercontent.com/114250271/197976195-240f5ec8-ae87-4f5a-9cad-926031d727e4.png)
Possible Solution: https://stackoverflow.com/questions/34189756/warning-about-ssl-connection-when-connecting-to-mysql-database

**Comment by danorris709** [comment]
Config issue
