### ISSUE TITLE
UltimatePokeBuilder Bugs and Suggestions

### ISSUE THREAD

**Issue by geumu** [EnvyWare/UltimatePokeBuilder#13]
**Mod**: UltimatePokeBuilder-Forge-2.1.2-1.16.5
**Operating System**: Windows 10 
**Bukkit Version**: arclight-forge-1.16.5-1.0.25-SNAPSHOT
**Java Version**: jdk-11.0.15.1
**Bugs and Suggestions**:
■ **Bugs**:
1. Changing the 'none-format: None' message in guis.yml does not change the message.
Image: https://imgur.com/a/hMwykAp

2. in guis.yml function 'commands_executed:' does not work.
guis.yml: https://pastebin.com/dCG9mCZE
Video: https://youtu.be/N_6r6mcz6AA

3. There is a bug where the title of the main GUI is changed to the title of the level when the 'Back button' is pressed after clicking the level item GUI.
guis.yml: https://pastebin.com/kTgKz3Pp
Video: https://youtu.be/tuv1emv5SMw

■ **Suggestions**:
1. It would be very convenient to have the value to be purchased, 
the value after change, and the total cost placeholders in 'Current Value:' in the EV, IV, and Level change items of guis.yml.
**Before change**: https://imgur.com/a/tVc9zph
**After change**: https://imgur.com/a/iU5oj2h
      
```guis.yml:
  Name: Current %iv% Value: %value%
  Lore:
  - '' 
  - 'Value to buy: %value_to_buy%'
  - 'value after change: %value_after_change%'
  - '' 
  - 'Total Price: %price% Token'
          
2. It would be really nice if UltimatePokeBuilder had an unbreedable feature.

**Comment by danorris709** [comment]
Sorted for next version
