### ISSUE TITLE
GUI title problem

### ISSUE THREAD

**Issue by geumu** [EnvyWare/UltimatePokeBuilder#15]
**Mod**: UltimatePokeBuilder-Forge-2.1.3-1.16.5
**Operating System**: Windows 10 
**Bukkit Version**: arclight-forge-1.16.5-1.0.25-SNAPSHOT
**Java Version**: jdk-11.0.15.1
■ **Bugs**:
1. I figured out why the titles in the Levels, IVs, and Evs GUI didn't change.

For GUIs such as Shiny, PokeBall, and Untradeable, the size of the box GUI is different, so the title changes because the GUI is refreshed.

The Level, IVs, and Evs GUIs don't seem to change the title because they only change the items without refreshing
because the box GUI is 4 lines like the main GUI.

If you look at the 6 second part of the video, you can see the problem.

Video: https://youtu.be/fH2evB70JCI

**Comment by danorris709** [comment]
This is an issue where the title won't change if you don't change the UI size
