### ISSUE TITLE
buttons not updating the menu

### ISSUE THREAD

**Issue by aglarcz** [EnvyWare/UltimatePokeBuilder#17]
Clicking the buttons doesnt update the menu, works only after clicking the glass elements.
With version 2.2.1-1.16.5 on Arclight.

![UPB_not_updating_gui](https://github.com/EnvyWare/UltimatePokeBuilder/assets/17107410/c8ca45cc-dc6b-496b-a437-ecc10dd97041)

**Comment by danorris709** [comment]
Fixed with latest
