### ISSUE TITLE
The permissions of the plugin aren't working

### ISSUE THREAD

**Issue by Zaureon** [EnvyWare/UltimatePokeBuilder#5]
I'm having a little trouble with the plugin, i already read the comand & permissions tab but the permission listed there aren't working, i tried everything, so this plugin are just working for OP players

I'm using Mohist and the latest plugin's version

**Comment by austin4195** [comment]
Have you attempted to look at an LP Verbose? Mohist does some weird stuff with permissions...

I had to grant the following permissions:
```
forgecommand.pokebuilder
minecraft.command.pokebuilder
yetanotherpokebuilder.command.pokebuilder
yetanotherpokebuilder.command.tokens
```

In the future, I would recommend running `/lp verbose record` attempting to run the command you are having issues with then running `/lp verbose paste` and seeing which permissions you are missing (they will be listed as false or undefined)

**Comment by Zaureon** [comment]
The permission forgecommand.pokebuilder worked perfectly, thank you so much
