### ISSUE TITLE
Untradeable UI button doesn't appear

### ISSUE THREAD

**Issue by SirDoof** [EnvyWare/UltimatePokeBuilder#7]
I tried changing values to see if it would appear but for some reason it doesn't (at least on my end)
https://gyazo.com/5c4bd48ba566ade9547d415c301bebec

**Comment by danorris709** [comment]
I'm not sure what you mean?

**Comment by SirDoof** [comment]
Like, in the main menu (after you select a pokemon), there's categories for editing the pokeball, nature, gender, etc and there should also be an Untradeable category but it doesn't appear even though it's specified in the config.
In the video clip you can see the empty spot.

**Comment by danorris709** [comment]
oh yes, I removed the untradeable feature because I thought no one was using it. Happy to add it back if wanted?

**Comment by SirDoof** [comment]
Yes please, thanks!

**Comment by danorris709** [comment]
Fixed for next version
